version: 0.2
env:
  secrets-manager:
    GIT_USER: "arn:aws:secretsmanager:us-east-1:652542735519:secret:git_push_build-c1PuHd:git_user"
    GIT_PASS: "arn:aws:secretsmanager:us-east-1:652542735519:secret:git_push_build-c1PuHd:git_pass"

phases:
  build:
    commands: |
      exec > outykk.out 2>&1
      git clone https://${GIT_USER}:${GIT_PASS}@git-codecommit.us-east-1.amazonaws.com/v1/repos/alfred ../monkey
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"

      echo "Hello Worlike!"

    finally: |
      mv outykk.out ../monkey
      cd ../monkey
      git add .
      git commit -m "funiek"
      git push


artifacts:
  files:
    - outy.out
  name: outier
  discard-paths: no
  base-directory: ./
  enable-symlinks: yes
